environment:
  GITHUB_TOKEN:
    secure: dgrPbnobrGhgoxC1D8WIA7iasLpFCIGKrLgZNBQ2J0xZBrprEsMHPDPxmnXmkdcz
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '7'
    - nodejs_version: '6'
    - nodejs_version: '4'
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: 'off'
